In [1]:
import numpy as np

In [3]:
x = np.array ([[25],[2],[-3],[-23]])
print (x)

[[ 25]
 [  2]
 [ -3]
 [-23]]


In [8]:
x_t = x.T
print (x_t)

[[ 25   2  -3 -23]]


In [9]:
import torch
import tensorflow as tf

In [13]:
v = torch.tensor ([[25],[2],[-3],[-23]])
print (v)

tensor([[ 25],
        [  2],
        [ -3],
        [-23]])


In [14]:
v_t = v.T
print (v)

tensor([[ 25],
        [  2],
        [ -3],
        [-23]])


In [22]:
z = tf.Variable ([[25],[2],[-3],[-23]])
print (z)

<tf.Variable 'Variable:0' shape=(4, 1) dtype=int32, numpy=
array([[ 25],
       [  2],
       [ -3],
       [-23]], dtype=int32)>


In [27]:
z_t = tf.transpose(z)
print (z_t)

tf.Tensor([[ 25   2  -3 -23]], shape=(1, 4), dtype=int32)
