Vectors (Rank 1 Tensors) in NumPy

In [1]:
import numpy as np

In [2]:
x = np.array([12, 12, 12])
x

array([12, 12, 12])

In [4]:
len(x)

3

In [5]:
x.shape

(3,)

In [6]:
type(x)

numpy.ndarray

In [8]:
x[0]

np.int64(12)

In [9]:
type(x[0])

numpy.int64

Vector Transposition

In [37]:
#lakukan transpose pada vector x dan simpan pada variabel x_tx_t = x.T
x_t

array([12, 12, 12])

In [38]:
#tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [39]:
#lakukan transpose pada vector y dan simpan pada variabel y_ty
y = np.array([[12, 12, 12]])
print(y.shape)
y_t = y.T
y_t

(1, 3)


array([[12],
       [12],
       [12]])

In [40]:
#tampilkan ukuran dari vector y_t
y_t.shape

(3, 1)

Vectors in PyTorch and TensorFlow

In [58]:
import torch
import tensorflow as tf

In [59]:
#lakukan transpose pada vector x dan simpan pada variabel x_pt
x_pt = torch.tensor([12, 12, 12])
x_pt

tensor([12, 12, 12])

In [60]:
#tampilkan ukuran dari vector x_pt
x_pt.shape

torch.Size([3])

In [61]:
#lakukan transpose pada vector y dan simpan pada variabel y_pt
y_pt = np.array([[12, 12, 12]])
print(y_pt.shape)
y_pt = y_pt.T
y_pt

(1, 3)


array([[12],
       [12],
       [12]])

In [62]:
#tampilkan ukuran dari vector y_pt
y_pt.shape

(3, 1)

In [63]:
#lakukan transpose pada vector x dan simpan pada variabel x_tf
x_tf = torch.tensor([12, 12, 12])
x_tf

tensor([12, 12, 12])

In [64]:
#tampilkan ukuran dari vector x_tf
x_tf.shape

torch.Size([3])

In [65]:
#lakukan transpose pada vector y dan simpan pada variabel y_tf
y_tf = np.array([[12, 12, 12]])
print(y_tf.shape)
y_tf = y_tf.T
y_tf

(1, 3)


array([[12],
       [12],
       [12]])

In [67]:
#tampilkan ukuran dari vector y_tf
y_tf.shape

(3, 1)