In [1]:
import numpy as np

In [7]:
#buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [8]:
#tampilkan ukuran dari matrix X
X.shape

(3, 2)

In [12]:
#tampilkan ukuran dari matrix X
X.size

6

In [13]:
##tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([25,  5,  3])

In [10]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([ 5, 26])

In [18]:
import torch
import tensorflow as tf

In [19]:
#ulangi soal nomor 1 menggunakan pytorch
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [20]:
#ulangi soal nomor 1 menggunakan pytorch
X_pt.shape

torch.Size([3, 2])

In [27]:
#ulangi soal nomor 1 menggunakan pytorch
X_pt.size


<function Tensor.size>

In [28]:
#ulangi soal nomor 1 menggunakan pytorch
X_pt[:,0]

tensor([25,  5,  3])

In [29]:
#ulangi soal nomor 1 menggunakan tensorflow
X_tf = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_tf

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [30]:
#ulangi soal nomor 1 menggunakan tensorflow
X_tf.shape

torch.Size([3, 2])

In [31]:
#ulangi soal nomor 1 menggunakan tensorflow
X_tf.size


<function Tensor.size>

In [32]:
#ulangi soal nomor 1 menggunakan tensorflow
X_tf[:,0]

tensor([25,  5,  3])